name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd front
          npm ci

      - name: Run frontend tests with coverage
        run: |
          cd front
          npm run test

      - name: Upload frontend coverage report
        uses: actions/upload-artifact@v4
        with:
          name: front-coverage
          path: front/coverage/

      - name: SonarCloud Scan (Frontend)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd front
          npx sonar-scanner \
            -Dproject.settings=../sonar-project.properties \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.typescript.lcov.reportPaths=coverage/bobapp/lcov.info \
            -Dsonar.token=$SONAR_TOKEN

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Compiler et tester Spring Boot
        run: |
          cd back
          mvn clean verify

      - name: Sauvegarder le rapport JaCoCo
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: back/target/site/jacoco/

      - name: SonarCloud Scan (Backend)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd back
          mvn -B sonar:sonar \
            -Dsonar.projectKey=AntoineGallou31_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD
            -Dsonar.organization=antoinegallou31
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=$SONAR_TOKEN \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

  docker:
    needs: [frontend, backend]
    runs-on: ubuntu-latest
    steps:
      # 1. Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Se connecter à Docker Hub
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # 3. Construire l'image backend
      - name: Build backend image
        run: docker build -t bobapp-backend ./back

      # 4. Construire l'image frontend
      - name: Build frontend image
        run: docker build -t bobapp-frontend ./front

      # 5. Pousser l'image backend sur Docker Hub
      - name: Push backend image
        run: |
          docker tag bobapp-backend ${{ secrets.DOCKER_USERNAME }}/bobapp-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/bobapp-backend:latest

      # 6. Pousser l'image frontend sur Docker Hub
      - name: Push frontend image
        run: |
          docker tag bobapp-frontend ${{ secrets.DOCKER_USERNAME }}/bobapp-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/bobapp-frontend:latest
