name: CI Docker + SonarCloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout backend code
        uses: actions/checkout@v4

      - name: Build backend Docker image
        run: |
          docker build -t bobapp-backend:latest -f back/Dockerfile .

      - name: Run backend container for test
        run: |
          docker run --rm -p 8080:8080 bobapp-backend:latest & sleep 20

      - name: Save JaCoCo coverage
        uses: actions/upload-artifact@v4
        with:
          name: backend-jacoco
          path: back/target/site/jacoco/

      - name: SonarCloud Scan (Backend)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd back
          mvn sonar:sonar \
            -Dsonar.projectKey=AntoineGallou31_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD \
            -Dsonar.organization=antoinegallou31 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout frontend code
        uses: actions/checkout@v4

      - name: Build frontend Docker image
        run: docker build -t bobapp-frontend:latest -f front/Dockerfile .

      - name: Run frontend container for test
        run: docker run --rm -p 80:80 bobapp-frontend:latest & sleep 10

      - name: Upload frontend coverage report
        uses: actions/upload-artifact@v4
        with:
          name: front-coverage
          path: front/coverage/

      - name: SonarCloud Scan (Frontend)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd front
          npx sonar-scanner \
            -Dsonar.sources=src \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.typescript.lcov.reportPaths=coverage/bobapp/lcov.info \
            -Dsonar.login=$SONAR_TOKEN


